name: Build

on:
  push:
    branches:
      - main
      - next

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [22, 24]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      # Turn off windows-defender for this folder to speed up compile
      - if: runner.os == 'Windows'
        name: windows-defender
        run: powershell -Command Add-MpPreference -ExclusionPath "."

      - name: install
        run: npm install

      - name: build
        run: npm run build
